
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_AAVEED/pooled/5-otherFormats_H3K27ac_AAVEED1.bgsub.Fnor.smooth.wig         --genefile_paths  0-Regions/isoform_exp_diff.bed   --genomic_sites  TSS,ESS,gene     --name 9-DANPOS/2-profileGenes/H3K27ac_AAVEED/H3K27ac_AAVEED1           --flank_up 4000   --flank_dn 4000  --region_size 8000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_AAVEED/pooled/5-otherFormats_H3K27ac_AAVEED2.bgsub.Fnor.smooth.wig         --genefile_paths  0-Regions/isoform_exp_diff.bed   --genomic_sites  TSS,ESS,gene     --name 9-DANPOS/2-profileGenes/H3K27ac_AAVEED/H3K27ac_AAVEED2           --flank_up 4000   --flank_dn 4000  --region_size 8000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_AAVGFP/pooled/5-otherFormats_H3K27ac_AAVGFP1.bgsub.Fnor.smooth.wig         --genefile_paths  0-Regions/isoform_exp_diff.bed   --genomic_sites  TSS,ESS,gene     --name 9-DANPOS/2-profileGenes/H3K27ac_AAVGFP/H3K27ac_AAVGFP1           --flank_up 4000   --flank_dn 4000  --region_size 8000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_AAVGFP/pooled/5-otherFormats_H3K27ac_AAVGFP2.bgsub.Fnor.smooth.wig         --genefile_paths  0-Regions/isoform_exp_diff.bed   --genomic_sites  TSS,ESS,gene     --name 9-DANPOS/2-profileGenes/H3K27ac_AAVGFP/H3K27ac_AAVGFP2           --flank_up 4000   --flank_dn 4000  --region_size 8000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        



danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_ctrl/pooled/5-otherFormats_H3K27ac_ctrl1.bgsub.Fnor.smooth.wig           --genefile_paths  0-Regions/isoform_exp_diff.bed   --genomic_sites  TSS,ESS,gene     --name 9-DANPOS/2-profileGenes/H3K27ac_ctrl/H3K27ac_ctrl1           --flank_up 4000   --flank_dn 4000  --region_size 8000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_ctrl/pooled/5-otherFormats_H3K27ac_ctrl2.bgsub.Fnor.smooth.wig           --genefile_paths  0-Regions/isoform_exp_diff.bed   --genomic_sites  TSS,ESS,gene     --name 9-DANPOS/2-profileGenes/H3K27ac_ctrl/H3K27ac_ctrl2           --flank_up 4000   --flank_dn 4000  --region_size 8000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_KO/pooled/5-otherFormats_H3K27ac_KO1.bgsub.Fnor.smooth.wig               --genefile_paths  0-Regions/isoform_exp_diff.bed   --genomic_sites  TSS,ESS,gene     --name 9-DANPOS/2-profileGenes/H3K27ac_KO/H3K27ac_KO1               --flank_up 4000   --flank_dn 4000  --region_size 8000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_KO/pooled/5-otherFormats_H3K27ac_KO2.bgsub.Fnor.smooth.wig               --genefile_paths  0-Regions/isoform_exp_diff.bed   --genomic_sites  TSS,ESS,gene     --name 9-DANPOS/2-profileGenes/H3K27ac_KO/H3K27ac_KO2               --flank_up 4000   --flank_dn 4000  --region_size 8000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        









danpos.py  profile  9-DANPOS/1-dpos/H3K27me3_AAVEED/pooled/5-otherFormats_H3K27me3_AAVEED1.bgsub.Fnor.smooth.wig         --genefile_paths  0-Regions/isoform_exp_diff.bed   --genomic_sites  TSS,ESS,gene     --name 9-DANPOS/2-profileGenes/H3K27me3_AAVEED/H3K27me3_AAVEED1           --flank_up 4000   --flank_dn 4000  --region_size 8000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27me3_AAVEED/pooled/5-otherFormats_H3K27me3_AAVEED2.bgsub.Fnor.smooth.wig         --genefile_paths  0-Regions/isoform_exp_diff.bed   --genomic_sites  TSS,ESS,gene     --name 9-DANPOS/2-profileGenes/H3K27me3_AAVEED/H3K27me3_AAVEED2           --flank_up 4000   --flank_dn 4000  --region_size 8000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27me3_AAVGFP/pooled/5-otherFormats_H3K27me3_AAVGFP1.bgsub.Fnor.smooth.wig         --genefile_paths  0-Regions/isoform_exp_diff.bed   --genomic_sites  TSS,ESS,gene     --name 9-DANPOS/2-profileGenes/H3K27me3_AAVGFP/H3K27me3_AAVGFP1           --flank_up 4000   --flank_dn 4000  --region_size 8000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27me3_AAVGFP/pooled/5-otherFormats_H3K27me3_AAVGFP2.bgsub.Fnor.smooth.wig         --genefile_paths  0-Regions/isoform_exp_diff.bed   --genomic_sites  TSS,ESS,gene     --name 9-DANPOS/2-profileGenes/H3K27me3_AAVGFP/H3K27me3_AAVGFP2           --flank_up 4000   --flank_dn 4000  --region_size 8000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        


danpos.py  profile  9-DANPOS/1-dpos/H3K27me3_ctrl/pooled/5-otherFormats_H3K27me3_ctrl1.bgsub.Fnor.smooth.wig         --genefile_paths  0-Regions/isoform_exp_diff.bed   --genomic_sites  TSS,ESS,gene     --name 9-DANPOS/2-profileGenes/H3K27me3_ctrl/H3K27me3_ctrl1           --flank_up 4000   --flank_dn 4000  --region_size 8000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27me3_ctrl/pooled/5-otherFormats_H3K27me3_ctrl2.bgsub.Fnor.smooth.wig         --genefile_paths  0-Regions/isoform_exp_diff.bed   --genomic_sites  TSS,ESS,gene     --name 9-DANPOS/2-profileGenes/H3K27me3_ctrl/H3K27me3_ctrl2           --flank_up 4000   --flank_dn 4000  --region_size 8000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27me3_ctrl/pooled/5-otherFormats_H3K27me3_ctrl3.bgsub.Fnor.smooth.wig         --genefile_paths  0-Regions/isoform_exp_diff.bed   --genomic_sites  TSS,ESS,gene     --name 9-DANPOS/2-profileGenes/H3K27me3_ctrl/H3K27me3_ctrl3           --flank_up 4000   --flank_dn 4000  --region_size 8000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27me3_KO/pooled/5-otherFormats_H3K27me3_KO1.bgsub.Fnor.smooth.wig             --genefile_paths  0-Regions/isoform_exp_diff.bed   --genomic_sites  TSS,ESS,gene     --name 9-DANPOS/2-profileGenes/H3K27me3_KO/H3K27me3_KO1               --flank_up 4000   --flank_dn 4000  --region_size 8000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27me3_KO/pooled/5-otherFormats_H3K27me3_KO2.bgsub.Fnor.smooth.wig             --genefile_paths  0-Regions/isoform_exp_diff.bed   --genomic_sites  TSS,ESS,gene     --name 9-DANPOS/2-profileGenes/H3K27me3_KO/H3K27me3_KO2               --flank_up 4000   --flank_dn 4000  --region_size 8000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        






