danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_AAVEED/pooled/5-otherFormats_H3K27ac_AAVEED1.bgsub.Fnor.smooth.wig         --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Up.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Up/H3K27ac_AAVEED1           --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_AAVEED/pooled/5-otherFormats_H3K27ac_AAVEED2.bgsub.Fnor.smooth.wig         --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Up.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Up/H3K27ac_AAVEED2           --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_AAVGFP/pooled/5-otherFormats_H3K27ac_AAVGFP1.bgsub.Fnor.smooth.wig         --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Up.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Up/H3K27ac_AAVGFP1           --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_AAVGFP/pooled/5-otherFormats_H3K27ac_AAVGFP2.bgsub.Fnor.smooth.wig         --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Up.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Up/H3K27ac_AAVGFP2           --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        

danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_ctrl/pooled/5-otherFormats_H3K27ac_ctrl1.bgsub.Fnor.smooth.wig             --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Up.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Up/H3K27ac_ctrl1             --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_ctrl/pooled/5-otherFormats_H3K27ac_ctrl2.bgsub.Fnor.smooth.wig             --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Up.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Up/H3K27ac_ctrl2             --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_KO/pooled/5-otherFormats_H3K27ac_KO1.bgsub.Fnor.smooth.wig                 --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Up.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Up/H3K27ac_KO1               --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_KO/pooled/5-otherFormats_H3K27ac_KO2.bgsub.Fnor.smooth.wig                 --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Up.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Up/H3K27ac_KO2               --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        








danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_AAVEED/pooled/5-otherFormats_H3K27ac_AAVEED1.bgsub.Fnor.smooth.wig         --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Down.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Down/H3K27ac_AAVEED1           --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_AAVEED/pooled/5-otherFormats_H3K27ac_AAVEED2.bgsub.Fnor.smooth.wig         --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Down.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Down/H3K27ac_AAVEED2           --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_AAVGFP/pooled/5-otherFormats_H3K27ac_AAVGFP1.bgsub.Fnor.smooth.wig         --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Down.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Down/H3K27ac_AAVGFP1           --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_AAVGFP/pooled/5-otherFormats_H3K27ac_AAVGFP2.bgsub.Fnor.smooth.wig         --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Down.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Down/H3K27ac_AAVGFP2           --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        

danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_ctrl/pooled/5-otherFormats_H3K27ac_ctrl1.bgsub.Fnor.smooth.wig             --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Down.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Down/H3K27ac_ctrl1             --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_ctrl/pooled/5-otherFormats_H3K27ac_ctrl2.bgsub.Fnor.smooth.wig             --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Down.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Down/H3K27ac_ctrl2             --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_KO/pooled/5-otherFormats_H3K27ac_KO1.bgsub.Fnor.smooth.wig                 --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Down.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Down/H3K27ac_KO1               --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_KO/pooled/5-otherFormats_H3K27ac_KO2.bgsub.Fnor.smooth.wig                 --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Down.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Down/H3K27ac_KO2               --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        










danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_AAVEED/pooled/5-otherFormats_H3K27ac_AAVEED1.bgsub.Fnor.smooth.wig         --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Nochange.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Nochange/H3K27ac_AAVEED1           --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_AAVEED/pooled/5-otherFormats_H3K27ac_AAVEED2.bgsub.Fnor.smooth.wig         --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Nochange.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Nochange/H3K27ac_AAVEED2           --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_AAVGFP/pooled/5-otherFormats_H3K27ac_AAVGFP1.bgsub.Fnor.smooth.wig         --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Nochange.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Nochange/H3K27ac_AAVGFP1           --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_AAVGFP/pooled/5-otherFormats_H3K27ac_AAVGFP2.bgsub.Fnor.smooth.wig         --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Nochange.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Nochange/H3K27ac_AAVGFP2           --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        

danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_ctrl/pooled/5-otherFormats_H3K27ac_ctrl1.bgsub.Fnor.smooth.wig             --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Nochange.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Nochange/H3K27ac_ctrl1             --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_ctrl/pooled/5-otherFormats_H3K27ac_ctrl2.bgsub.Fnor.smooth.wig             --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Nochange.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Nochange/H3K27ac_ctrl2             --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_KO/pooled/5-otherFormats_H3K27ac_KO1.bgsub.Fnor.smooth.wig                 --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Nochange.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Nochange/H3K27ac_KO1               --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        
danpos.py  profile  9-DANPOS/1-dpos/H3K27ac_KO/pooled/5-otherFormats_H3K27ac_KO2.bgsub.Fnor.smooth.wig                 --bed3file_paths  0-Regions/FeiDiffGenesCoordinates/Nochange.bed       --name 9-DANPOS/FeiDiffGenesCoordinates/H3K27ac/Nochange/H3K27ac_KO2               --flank_up 5000   --flank_dn 5000  --region_size 1000          --heatmap 1  --plot_row 1   --plot_column 1   --plot_colors green        --bin_size 20                                        






